### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by darkskull009** [victorvoid/space-jekyll-template#33]
Hello I'm just newbie in this Jekyll theme can you point me out ho to change dark purple of this space theme.
Thanks in advance

**Comment by victorvoid** [comment]
No problem, you can go in the [variable.styl](https://github.com/victorvoid/space-jekyll-template/blob/master/src/styl/_variables.styl) and modify the colors. 

[Follow these steps to be able to compile](https://github.com/victorvoid/space-jekyll-template#how-can-i-modify-the-theme-)

**Comment by darkskull009** [comment]
Thanks once again

**Comment by darkskull009** [comment]
I found the file but nothing happens

**Comment by darkskull009** [comment]
Brother I'm new in this jekyll and i use android phone not laptop

**Comment by victorvoid** [comment]
Sorry, but you need a laptop to compile the changes.

**Comment by darkskull009** [comment]
As you said i used my friends laptop he is running Ubuntu 64bit latest version and i got this error
throw err;
    ^

Error: Cannot find module 'gulp-plumber'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/home/Desktop/fallenangle.github.io/gulpfile.js:2:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by victorvoid** [comment]
You need install the dependencies using [npm](https://www.npmjs.com/) (I assume you have pre-installed [node.js](https://nodejs.org/)): 

```
npm install
```

**Comment by darkskull009** [comment]
Still not working

**Comment by victorvoid** [comment]
Because the problem is not exactly this project, I'm closing this issue.
